#!/app/busybox/current/bin/sh

if [ "$1" = "" ]; then
  echo Please provide page name
  exit
fi

FOUND_PATH=""
APP_LIST=$(/app/busybox/current/bin/ls /app)
for APP_NAME in $APP_LIST; do
  if [ -e "/app/${APP_NAME}/current/readme.md" ]; then
    sectionMan=0
    while read -r line; do
      if [ "$line" = "**Man**" ]; then
        sectionMan=1
      elif [ "$line" = "" ]; then
        sectionMan=0;
      elif [ "$sectionMan" = 1 ]; then
        IFS=":"
        for folder in $line; do
          if [ -d "/app/${APP_NAME}/current/$folder" ]; then
            lsls=$(ls "/app/${APP_NAME}/current/$folder" | grep $1)
            if [ "$lsls" != "" ]; then
              if [ "$FOUND_PATH" != "" ]; then
                FOUND_PATH="$FOUND_PATH "
              fi
              FOUND_PATH="$FOUND_PATH$lsls"
            fi
            for nr in 1 2 3 4 5 6 7 8 9; do
              if [ -e "/app/${APP_NAME}/current/$folder/$1.$nr" ]; then
                # search for redirection in file. It's ".so filename" string in the first line
                while read -r line2; do
                  case $line2 in
                  *.so\ man*)
                    IFS=" " read -r HEAD FILENAME << EOF
$line2
EOF
                    if [ -e "/app/${APP_NAME}/current/$folder/../$FILENAME" ]; then
                      OUT=$(groff -man -Tutf8 -E -M /app/groff/current/share/groff/current/tmac \
                        -F /app/groff/current/share/groff/current/font \
                        "/app/${APP_NAME}/current/$folder/../$FILENAME")
                      echo $OUT 2> /dev/null | less -R -M -s
                      exit
                    fi
                  esac
                done < "/app/${APP_NAME}/current/$folder/$1.$nr"
                OUT=$(groff -man -Tutf8 -E -M /app/groff/current/share/groff/current/tmac \
                   -F /app/groff/current/share/groff/current/font \
                   "/app/${APP_NAME}/current/$folder/$1.$nr")
                echo $OUT 2> /dev/null | less -R -M -s
                exit
              elif [ -e "/app/${APP_NAME}/current/$folder/$1.$nr.gz" ]; then
                OUT=$(gunzip -c "/app/${APP_NAME}/current/$folder/$1.$nr.gz" | \
                groff -man -Tutf8 -E -M /app/groff/current/share/groff/current/tmac \
                   -F /app/groff/current/share/groff/current/font)
                echo $OUT 2> /dev/null | less -R -M -s
                exit
              fi
            done
          fi
        done
      fi
    done < /app/${APP_NAME}/current/readme.md
  fi
done
echo "$1 not found. Some other pages with this string"
echo
echo "$FOUND_PATH"
