#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
	menuentry 'PLLINUX' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'PL2' {
		set root='hd1,gpt1'		
		echo	'Loading PLLINUX ...'
		linux	/app/kernel/current/bzImage root=UUID=********************* rw
		initrd /app/kernel/current/initramfs.gz
	}
