#!/bin/sh

/bin/mount -t devtmpfs devtmpfs /dev
/bin/mount -t proc proc /proc

KERNEL_PARAMS=$(cat /proc/cmdline $X | /usr/bin/tr " ")
ROOT_DEVICE_ID=""
for PARAM in $KERNEL_PARAMS
do
  if [ "${PARAM:0:5}" == "root=" ]; then
     ROOT_DEVICE_ID=${PARAM#root=}
  fi
done
ROOT_DEVICE_NAME=$(/sbin/blkid | grep ${ROOT_DEVICE_ID#UUID=})

/bin/fsck.ext4 ${ROOT_DEVICE_NAME%%:*}
/bin/mount -t ext4 $ROOT_DEVICE_ID /mnt
if [ $? -ne 0 ]; then
  exec /bin/sh < /dev/console > /dev/console 2>&1
else
  cd /mnt

  /bin/mount -t devtmpfs devtmpfs dev
  /bin/mount -t proc proc proc
  /bin/mount -t tmpfs tmpfs run
  /bin/mount -t sysfs sysfs sys

  exec switch_root . "/app/dinit/current/dinit" "$@"
fi
