module(load="imuxsock")
module(load="imklog")

kern.*           /log/tmp/kernel
daemon.*          /log/tmp/services
auth,authpriv.*       /log/tmp/auth
syslog.*            /log/tmp/syslog
cron.*             /log/tmp/cron
