# Created by script pllinux
module(load="imuxsock") #SysSock . Annotate=on #local system logging
module(load="imkmsg") #kernel boot messages (from ring buffer and /dev/kmsg). Cannot be used with imklog module
auth.* /log/tmp/auth
cron.* /log/tmp/cron
daemon.* /log/tmp/services
kern.* /log/tmp/kernel
syslog.* /log/tmp/syslog
