#!/app/busybox/current/bin/sh
DIR=$(/app/busybox/current/bin/dirname $0)
/app/ldso/current/ld.so --library-path /app/zlib/current/lib:/app/zstd/current/lib:/app/libc/current:$DIR/lib $DIR/bin/rsync $@
