#!/app/busybox/current/bin/sh
DIR=$(dirname $0)
if [ -d "/etc." ]; then
  # root
  APP=" --dev dev --bind /app app --bind $DIR/etc/mc etc/mc "
else
  # non root
  APP=" --dev dev --ro-bind /app app --ro-bind $DIR/etc/mc etc/mc --ro-bind /etc/localtime etc/localtime "
fi
if [ -d "/iso" ]; then
  # iso image
  APP3=""
else
  # normal system
  APP3=" --chdir $(pwd) ";
fi
mkdir /other/app/mc 2> /dev/null
/app/bwrap/current/bin/bwrap \
    --setenv HOME /other/app/mc \
    $APP \
    --dev-bind-try /dev/pts/ptmx /dev/pst/ptmx \
    --proc proc \
    --bind /tmp tmp \
    --bind-try /run run \
    --bind-try /mnt mnt \
    --bind /home home \
    --bind-try /other other \
    --bind-try /etc. etc \
    --ro-bind $DIR/bin bin \
    --ro-bind /lib64 lib64 \
    --setenv PS1 "[\t] $USER # " \
    --setenv SHELL /app/busybox/current/bin/sh \
    $APP3 \
    $DIR/bin/mc
    # no clean before running command in options
# -u will disable subshell
# don't show internal commands from MC in the shell history
#    --setenv HISTCONTROL ignorespace \
#    --ro-bind $DIR/usr usr \
#    --tmpfs tmp \
