#!/app/busybox/current/bin/sh
DIR=$(dirname $0)
APP=" --ro-bind /app app "
APP2=" --ro-bind $DIR/etc/mc etc/mc "
if [ -d "/etc." ]; then 
  APP=" --bind /app app "; 
  APP2=" --bind $DIR/etc/mc etc/mc "
fi
mkdir /other/app/mc 2> /dev/null
/app/bwrap/current/bin/bwrap \
    --setenv HOME /other/app/mc \
    --dev dev \
    --dev-bind-try /dev/pts/ptmx /dev/pst/ptmx \
    --proc proc \
    --tmpfs tmp \
    --bind-try /run run \
    --bind /mnt mnt \
    --bind /home home \
    --bind-try /other other \
    --bind-try /etc. etc \
    $APP2 \
    $APP \
    --ro-bind $DIR/bin bin \
    --ro-bind $DIR/usr usr \
    --ro-bind /lib64 lib64 \
    --setenv PS1 "[\t] $USER # " \
    --setenv SHELL /app/busybox/current/bin/sh \
    --chdir $(pwd) \
    $DIR/bin/mc
# don't show internal commands from MC in the shell history
#    --setenv HISTCONTROL ignorespace \
