#!/app/busybox/current/bin/sh
DIR=$(dirname $0)
/app/ldso/current/ld.so --library-path /app/glib/current/lib:/app/slang/current/lib:/app/libc/current/lib:/app/pcre2/current/lib:/app/gcc/current/lib:$DIR/../lib --argv0 $0 $DIR/mc $@
