#!/app/busybox/current/bin/sh

export PATH=/app/busybox/current/bin

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t tmpfs tmpfs /mnt
mount -t tmpfs tmpfs /run
mount -t sysfs sysfs /sys

cd mnt
mkdir iso
mount -t iso9660 /dev/sr0 iso

mkdir app
/app/rsync/current/bin/rsync -a iso/app/ app

mkdir bin
mkdir dev

mkdir etc
/app/rsync/current/bin/rsync -a iso/etc/ etc

mkdir home

mkdir home/root
chown 0 home/root
chgrp 0 home/root
mkdir home/root/app
chown 0 home/root/app
chgrp 0 home/root/app
mkdir home/root/files
chown 0 home/root/files
chgrp 0 home/root/files
chmod u+rwx home/root
chmod g-rwx home/root
chmod o-rwx home/root

mkdir home/user
chown 1000 home/user
chgrp 1000 home/user
mkdir home/user/app
chown 1000 home/user/app
chgrp 1000 home/user/app
mkdir home/user/files
chown 1000 home/user/files
chgrp 1000 home/user/files
chmod u+rwx home/user
chmod g-rwx home/user
chmod o-rwx home/user

mkdir home/user2
chown 1001 home/user2
chgrp 1001 home/user2
mkdir home/user2/app
chown 1001 home/user2/app
chgrp 1001 home/user2/app
mkdir home/user2/files
chown 1001 home/user2/files
chgrp 1001 home/user2/files
chmod u+rwx home/user2
chmod g-rwx home/user2
chmod o-rwx home/user2

mkdir mnt
mkdir proc
mkdir run
mkdir sys
mkdir tmp
mkdir lib64
if [ ! -d "etc." ]; then ln -s etc etc.; fi
if [ ! -d "other" ]; then ln -s home/root other; fi
cd bin
ln -s /sh sh
ln -s /app/bash/current/bin/bash bash
cd ..
cd lib64
ln -s /app/glibc/current/lib/ld-linux-x86-64.so.2 ld-linux-x86-64.so.2
chmod a+x ld-linux-x86-64.so.2
cd ..

mount -t devtmpfs devtmpfs dev
mount -t proc proc proc
mount -t tmpfs tmpfs mnt
mount -t tmpfs tmpfs run
mount -t sysfs sysfs sys

#exec sh < /dev/console > /dev/console 2>&1

export SHELL=/app/busybox/current/bin/sh
exec /app/busybox/current/sbin/switch_root . "/app/dinit/current/bin/dinit" "$@"
