#!/app/busybox/current/bin/sh

export PATH=/app/busybox/current/bin

mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc

KERNEL_PARAMS=$(cat /proc/cmdline $X | tr " ")
ROOT_DEVICE_ID=""
for PARAM in $KERNEL_PARAMS
do
  if [ "${PARAM:0:5}" == "root=" ]; then
     ROOT_DEVICE_ID=${PARAM#root=}
  fi
done
#ROOT_DEVICE_NAME=$(/app/busybox/current/sbin/blkid | grep ${ROOT_DEVICE_ID#UUID=})

if [ "$ROOT_DEVICE_ID" == "" ] || [ "$ROOT_DEVICE_ID" == "rsync" ]; then
  # we don't have filesystem param or we have rsync
  # this looks like booting from iso
  mount -t tmpfs tmpfs /mnt
  mount -t tmpfs tmpfs /run
  mount -t sysfs sysfs /sys

  mkdir /mnt/iso
  mount -t iso9660 /dev/sr0 /mnt/iso

  cd /app
  for app in glibc openssl rsync zlib zstd; do ln -s /mnt/iso/app/$app $app; done

  cd /mnt

  if [ "$ROOT_DEVICE_ID" = "rsync" ]; then
    mkdir app
    echo "Copying /app from ISO to the RAM. This will need some time (even 20-30 seconds)"
    /app/rsync/current/bin/rsync -a --info=progress2 iso/app/ app
  else
    ln -s /iso/app app
  fi

#  mkdir app
#  for APP_NAME in $(ls /mnt/iso/app); do
#    mkdir /mnt/app/$APP_NAME
#    cd /mnt/app/$APP_NAME
#    for APP_VER in $(ls /mnt/iso/app/$APP_NAME); do
#      if [ "$APP_VER" != "current" ]; then
#        ln -s ../../iso/app/$APP_NAME/$APP_VER $APP_VER
#        ln -s /iso/app/$APP_NAME/$APP_VER $APP_VER
#        if [ "$(readlink /mnt/iso/app/$APP_NAME/current)" == "$APP_VER" ]; then
#          ln -s $APP_VER current
#        fi
#      fi
#    done
#  done
#  cd /mnt

  for folderentry in bin dev etc home mnt proc run sys tmp lib64; do mkdir $folderentry; done

  /app/rsync/current/bin/rsync -a --info=progress2 iso/etc/ etc

  for userentry in root user user2; do 
    case $userentry in
      root) GRP=0 ;;
      user) GRP=1000 ;;
      user2) GRP=1001 ;;
    esac

    for direntry in home/$userentry home/$userentry/app home/$userentry/files; do
      mkdir $direntry
      chown $GRP $direntry
      chgrp $GRP $direntry
    done

    chmod u+rwx $output/home/$userentry
    chmod g-rwx $output/home/$userentry
    chmod o-rwx $output/home/$userentry
  done

  if [ ! -d "etc." ]; then ln -s etc etc.; fi
  if [ ! -d "other" ]; then ln -s home/root other; fi

  cd bin
  ln -s /sh sh
  ln -s /app/bash/current/bin/bash bash
  cd ..

  cd lib64
  ln -s /app/glibc/current/lib/ld-linux-x86-64.so.2 ld-linux-x86-64.so.2
  chmod a+x ld-linux-x86-64.so.2
  cd ..
else
  # we have real filesystem param
  # this looks like booting from disk
  mount -r -t ext4 $ROOT_DEVICE_ID /mnt > /dev/null 2>&1
  cd /mnt
fi

mount -t devtmpfs devtmpfs dev
mount -t proc proc proc
mount -t tmpfs tmpfs mnt
mount -t tmpfs tmpfs run
mount -t sysfs sysfs sys

export SHELL=/app/busybox/current/bin/sh
exec /app/busybox/current/sbin/switch_root . "/app/dinit/current/bin/dinit" "$@"

#if [ $? -ne 0 ]; then
#exec sh < /dev/console > /dev/console 2>&1
