#!/app/busybox/current/bin/sh

/app/busybox/current/bin/mount -t devtmpfs devtmpfs /dev
/app/busybox/current/bin/mount -t proc proc /proc

KERNEL_PARAMS=$(/app/busybox/current/bin/cat /proc/cmdline $X | /app/busybox/current/bin/tr " ")
ROOT_DEVICE_ID=""
for PARAM in $KERNEL_PARAMS
do
  if [ "${PARAM:0:5}" == "root=" ]; then
     ROOT_DEVICE_ID=${PARAM#root=}
  fi
done
ROOT_DEVICE_NAME=$(/app/busybox/current/sbin/blkid | /app/busybox/current/bin/grep ${ROOT_DEVICE_ID#UUID=})

/app/busybox/current/bin/mount -r -t ext4 $ROOT_DEVICE_ID /mnt > /dev/null 2>&1
#if [ $? -ne 0 ]; then
#  exec /app/busybox/current/bin/sh < /dev/console > /dev/console 2>&1
#else
  cd /mnt

  /app/busybox/current/bin/mount -t devtmpfs devtmpfs dev
  /app/busybox/current/bin/mount -t proc proc proc
  /app/busybox/current/bin/mount -t tmpfs tmpfs mnt
  /app/busybox/current/bin/mount -t tmpfs tmpfs run
  /app/busybox/current/bin/mount -t sysfs sysfs sys

  export SHELL=/app/busybox/current/bin/sh
  exec /app/busybox/current/sbin/switch_root . "/app/dinit/current/bin/dinit" "$@"
#fi
