#!/app/busybox/current/bin/sh
# Part of PLLINUX. Version from 2 Aug 2026. Creating system cfg from cfg file or asking user and creating cfg file.

DIR="/" # path with / in the end. In real system /
if [ -d "/mnt/x" ]; then
  DIR="/mnt/x/"
fi

set_config() {
if [ -e "$CFGFILE" ]; then
  while read -r line; do
    IFS="=" read -r PARAM_NAME PARAM_VALUE << EOF
$line
EOF
    case $PARAM_NAME in
    KEYB* )
      /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$PARAM_VALUE
      KEYB=$PARAM_VALUE
      OPT=""
      ;;
    FONT* )
      /app/kbd/current/bin/setfont -C /dev/tty1 $PARAM_VALUE 2> /dev/null
      /app/kbd/current/bin/setfont -C /dev/tty2 $PARAM_VALUE 2> /dev/null
      /app/kbd/current/bin/setfont -C /dev/tty3 $PARAM_VALUE 2> /dev/null
      /app/kbd/current/bin/setfont -C /dev/tty4 $PARAM_VALUE 2> /dev/null
      FONT=$PARAM_VALUE
      OPT=""
      ;;
    TIMEZONE* )
      CURRENT=$(/app/busybox/current/bin/realpath /etc/localtime)
      case $CURRENT in
        *$PARAM_VALUE* )
          # save SSD writes. Don't make link when it's there.
          ;;
        * )
          echo Setting timezone $PARAM_VALUE
          rm /etc/localtime
          ln -s /app/tzdb/current/usr/share/zoneinfo/$PARAM_VALUE /etc/localtime
      esac
      TIMEZONE=$PARAM_VALUE
      ;;
    LANG* )
#    echo $PARAM_VALUE
      list=$(/app/glibc/current/bin/locale -a)
      case $list in
        *$PARAM_VALUE*)
          ;;
        *)
          echo Generating locale
          mkdir /app/glibc/current/lib/locale
          #localedef -i pl_PL -c -f UTF-8 pl_PL.UTF-8
          localedef -i en_US -c -f UTF-8 en_US.UTF-8
          ;;
      esac
      LANG=$PARAM_VALUE
      ;;
    esac
  done < $CFGFILE
fi
}

set_keyboard_font() {
  KEYB2=$KEYB
  FONT2=$FONT
  while true; do
    /app/kbd/current/bin/setfont -C /dev/tty1 $FONT2
    /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$KEYB2
    cmd=$(dialog --stdout --backtitle "PLLinux/Keyboard and font" --cancel-label "Back" \
           --menu "Keyboard $KEYB2, font $FONT2" 0 0 5 \
           1 "Check" \
           2 "Set default" \
           3 "Set font" \
           4 "Set keyboard" \
           5 "Save and back")
    if [ $? == 0 ]; then
      case $cmd in
      1) $(dialog --stdout --backtitle "PLLinux/Keyboard and font/Check" --cancel-label "Back" \
                --inputbox "Please test your keyboard layout" 15 30) ;;
      2)  cmd=$(dialog --stdout --backtitle "PLLinux/Keyboard and font/set default" --cancel-label "Back" \
           --menu "Set proposed option for the concrete language" 0 0 5 \
           1 "PL" 2 "Other")
           if [ $? == 0 ]; then
             case $cmd in
               1) KEYB2="qwerty/pl1.map.gz"
                  FONT2="LatGrkCyr-8x16.psfu.gz"
                  ;;
               *) KEYB2="qwerty/pl4.map.gz"
                  FONT2="sun12x22.psfu.gz"
                  ;;
             esac
           fi
        ;;
      3) 
         list=""
         listnr=1
        for NAME in $(ls /app/kbd/current/share/consolefonts); do
          case $NAME in
            README*)
              ;;
            *)
              list="$list $listnr $NAME"
              listnr=$(($listnr+1))
              ;;
          esac
        done
        cmd=$(dialog --stdout --backtitle "PLLinux/Keyboard and font/set font" --cancel-label "Back" \
           --menu "Select font" 0 0 10 $list)
        if [ $? == 0 ]; then
          listnr=1
          for NAME in $(ls /app/kbd/current/share/consolefonts); do
            case $NAME in
              README*)
                ;;
              *)
                if [ $listnr = $cmd ]; then
                  FONT2="$NAME"
                fi
                listnr=$(($listnr+1))
                ;;
            esac
          done
        fi
        ;;
      4)
         list=""
         listnr=1
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/qwerty); do
              list="$list $listnr qwerty/$NAME"
              listnr=$(($listnr+1))
        done
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/qwertz); do
              list="$list $listnr qwertz/$NAME"
              listnr=$(($listnr+1))
        done
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/azerty); do
              list="$list $listnr azerty/$NAME"
              listnr=$(($listnr+1))
        done
        cmd=$(dialog --stdout --backtitle "PLLinux/Keyboard and font/set keyboard" --cancel-label "Back" \
           --menu "Select keyboard" 0 0 10 $list)
         listnr=1
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/qwerty); do
                if [ $listnr = $cmd ]; then
                  KEYB2="qwerty/$NAME"
                fi
              listnr=$(($listnr+1))
        done
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/qwertz); do
                if [ $listnr = $cmd ]; then
                  KEYB2="qwertz/$NAME"
                fi
              listnr=$(($listnr+1))
        done
        for NAME in $(ls /app/kbd/current/share/keymaps/i386/azerty); do
                if [ $listnr = $cmd ]; then
                  KEYB2="azerty/$NAME"
                fi
              listnr=$(($listnr+1))
        done
        ;;
      5)
        break;
        ;;
      esac
    else
      KEYB2=$KEYB
      FONT2=$FONT
      return
    fi
  done
  KEYB=$KEYB2
  FONT=$FONT2
  /app/kbd/current/bin/setfont -C /dev/tty1 $FONT
  /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$KEYB
}

set_time_zone() {
    list=""
    listnr=1
    for NAME in $(ls /app/tzdb/current/usr/share/zoneinfo); do
      if [ -d "/app/tzdb/current/usr/share/zoneinfo/$NAME" ]; then
        for NAME2 in $(ls /app/tzdb/current/usr/share/zoneinfo/$NAME); do
          list="$list $listnr $NAME/$NAME2"
          listnr=$(($listnr+1))
        done
      else
        list="$list $listnr $NAME"
        listnr=$(($listnr+1))
      fi
    done
    cmd=$(dialog --stdout --backtitle "PLLinux/set timezone" --cancel-label "Back" \
           --menu "Selected timezone $TIMEZONE. Please select new value" 0 0 10 $list)
    if [ $? = 0 ]; then
      listnr=1
      for NAME in $(ls /app/tzdb/current/usr/share/zoneinfo); do
        if [ -d "/app/tzdb/current/usr/share/zoneinfo/$NAME" ]; then
          for NAME2 in $(ls /app/tzdb/current/usr/share/zoneinfo/$NAME); do
            if [ $listnr = $cmd ]; then
              TIMEZONE=$NAME/$NAME2
            fi
            listnr=$(($listnr+1))
          done
        else
          if [ $listnr = $cmd ]; then
            TIMEZONE=$NAME
          fi
          listnr=$(($listnr+1))
        fi
      done
    fi
}

add_new_user() {
    cmd=$(dialog --stdout --backtitle "PLLinux/set users/add new user" --cancel-label "Back" \
           --menu "Edit users" 0 0 10 1 "x")
}

set_existing_user() {
    cmd=$(dialog --stdout --backtitle "PLLinux/set users/set user" --cancel-label "Back" \
           --menu "Edit users" 0 0 10 1 "x")
}


set_users() {
  while true; do
    listnr=1
    list=""
    while read -r line; do
      IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
      list="$list $listnr $USER_NAME"
      listnr=$(($listnr+1))
    done < "${DIR}etc/passwd"
    list="$list $listnr Add"
    cmd=$(dialog --stdout --backtitle "PLLinux/set users" --cancel-label "Back" \
           --menu "Edit users" 0 0 10 $list)
    if [ $? = 0 ]; then
      listnr=1
      while read -r line; do
        IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
        if [ $listnr = $cmd ]; then
          set_existing_user $USER_NAME
        fi
        listnr=$(($listnr+1))
    done < "${DIR}etc/passwd"
        if [ $listnr = $cmd ]; then
          add_new_user
        fi
    else
      break;
    fi
  done
}

# some default values
TIMEZONE="UTC"
KEYB="qwerty/pl4.map.gz"
FONT="sun12x22.psfu.gz"
LANG="en_US.UTF-8"

CFGFILE="/etc/pllinux.conf"
if [ "$1" != "" ]; then
  CFGFILE="$1"
fi
set_config
if [ "$1" != "" ]; then
  if [ "$2" = "LANG" ]; then
    echo $LANG
  fi
  exit
fi

while true; do
  cmd=$(dialog --stdout --backtitle "PLLinux" --cancel-label "Quit" --menu "Welcome to the PLLinux configuration" 0 0 4 \
       1 "Keyboard and font - $KEYB, $FONT" \
       2 "Set timezone      - $TIMEZONE" \
       3 "Users" \
       4 "Save and exit")
  if [ $? == 0 ]; then
    case $cmd in
    1) set_keyboard_font ;;
    2) set_time_zone ;;
    3) set_users ;;
    4) break ;;
    esac
  else
    return
  fi
done

#FIXME: dont save, when file is not updated. Save SSD
echo "# Created by script pllinux version from 2 Aug 2026" > /etc/pllinux.conf
echo "KEYB=$KEYB" >> /etc/pllinux.conf
echo "FONT=$FONT" >> /etc/pllinux.conf
echo "TIMEZONE=$TIMEZONE" >> /etc/pllinux.conf
echo "LANG=en_US.utf8" >> /etc/pllinux.conf

set_config
