#!/app/busybox/current/bin/sh
# Part of PLLINUX. Version from 9 Aug 2026. Creating system cfg from conf file or asking user and creating conf file.

DIR="/" # path with / in the end. In real system /
if [ -d "/mnt/x" ]; then
  DIR="/mnt/x/"
fi
if [ -d "/pllinux" ]; then
  DIR="/pllinux/"
fi

IFSORIG=$IFS

SYSTEM_APPS="dialog:gcc:glib:glibc:gptfdisk:groff:ncurses:ncursesw:rsync:wget2:parted:busybox:bwrap:dinit:e2fsprogs:initramfs:kbd:kernel:ldso:libc:libtinfo:nftables:pllinux:util-linux" # we cannot remove "current" version for these apps

# some default values
TIMEZONE="UTC"
KEYB="qwerty/pl4.map.gz"
FONT="sun12x22.psfu.gz"
LANG="en_US.UTF-8"

FIRST_SAVE=1

change_value_in_conf_file() {
  if [ "$FIRST_SAVE" = "1" ]; then
     cp ${DIR}$CFGFILE ${DIR}${CFGFILE}-
     FIRST_SAVE=0
  fi
  file_content=$(cat ${DIR}$CFGFILE)
  echo "# Created by script pllinux version from 2 Aug 2026" > ${DIR}$CFGFILE
  while IFS= read -r line; do
    IFS="=" read -r PARAM_NAME PARAM_VALUE << EOF
$line
EOF
    if [ "$PARAM_NAME" != "$1" ] && [ ${line:0:1} != "#" ]; then
      echo "$line" >> ${DIR}$CFGFILE
    fi
  done <<< "$file_content"
  echo "$1=$2" >> ${DIR}$CFGFILE
  IFS=$IFSORIG
}

get_value_from_conf_file() {
  CONF_FILE_VALUE=""
  while read -r line; do
    IFS="=" read -r PARAM_NAME PARAM_VALUE << EOF
$line
EOF
    case $PARAM_NAME in
    $1* )
      CONF_FILE_VALUE=$PARAM_VALUE
      ;;
    esac
  done < $DIR$CFGFILE
  IFS=$IFSORIG
}

set_general_config() {
  if [ "$DIR" != "/" ]; then
    return
  fi
  if [ -e "$DIR$CFGFILE" ]; then
    while read -r line; do
      IFS="=" read -r PARAM_NAME PARAM_VALUE << EOF
$line
EOF
      case $PARAM_NAME in
      KEYB* )
        if [ "$1" = "1" ]; then
           /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$PARAM_VALUE
        fi
        KEYB="$PARAM_VALUE" ;;
      FONT* )
        if [ "$1" = "1" ]; then
          for DEVDEV in 1 2 3 4; do
            /app/kbd/current/bin/setfont -C /dev/tty$DEVDEV $PARAM_VALUE 2> /dev/null
          done
        fi
        FONT="$PARAM_VALUE" ;;
      TIMEZONE* )
        CURRENT=$(/app/busybox/current/bin/realpath /etc/localtime)
        case $CURRENT in
          *$PARAM_VALUE*)
            # save SSD writes. Don't make link when it's there.
            ;;
          *)
            echo Setting timezone $PARAM_VALUE
            rm /etc/localtime
            ln -s /app/tzdb/current/usr/share/zoneinfo/$PARAM_VALUE /etc/localtime
        esac
        TIMEZONE=$PARAM_VALUE ;;
      LANG* )
        list=$(/app/glibc/current/bin/locale -a)
        case $list in
          *$PARAM_VALUE*)
            ;;
          *)
            echo Generating locale
            mkdir /app/glibc/current/lib/locale
            #localedef -i pl_PL -c -f UTF-8 pl_PL.UTF-8
            localedef -i en_US -c -f UTF-8 en_US.UTF-8 ;;
        esac
        LANG=$PARAM_VALUE ;;
      esac
    done < $DIR$CFGFILE
  fi
}

set_keyboard_font_general_or_user() {
  if [ "$1" = "" ]; then
    PROMPT="PLLinux";
    PROMPT2="";
  else
    PROMPT="PLLinux\set users\\$1";
    PROMPT2=" for $1";
  fi
  while true; do
    /app/kbd/current/bin/setfont -C /dev/tty1 $NEW_FONT
    /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$NEW_KEYB
    cmd=$(dialog --stdout --backtitle "$PROMPT\keyboard and font" --cancel-label "Back" \
           --menu "Set display and typing$PROMPT2" 0 0 5 \
           1 "Check" \
           2 "Set default" \
           3 "Set font     - $NEW_FONT" \
           4 "Set keyboard - $NEW_KEYB" \
           5 "Save and back")
    if [ $? == 0 ]; then
      case $cmd in
      1) $(dialog --stdout --backtitle "$PROMPT\keyboard and font\check" --cancel-label "Back" \
                --inputbox "Please test your keyboard layout" 15 30) ;;
      2) cmd=$(dialog --stdout --backtitle "$PROMPT\keyboard and font\set default" --cancel-label "Back" \
           --menu "Set proposed option for concrete language" 0 0 5 \
             1 "PL" 2 "Other")
           if [ $? == 0 ]; then
             NEW_KEYB="qwerty/pl4.map.gz"
             NEW_FONT="sun12x22.psfu.gz"
             case $cmd in
               1) NEW_KEYB="qwerty/pl1.map.gz"
                  NEW_FONT="LatGrkCyr-8x16.psfu.gz" ;;
             esac
           fi
           ;;
      3) list=""
         listnr=1
         for NAME in $(ls /app/kbd/current/share/consolefonts); do
           case $NAME in
             README*)
                ;;
             *) list="$list $listnr $NAME"
                if [ "$NEW_FONT" == "$NAME" ]; then
                  DEFAULT_NUM=$listnr
                fi
                listnr=$(($listnr+1))
                ;;
           esac
         done
         cmd=$(dialog --stdout --backtitle "$PROMPT\keyboard and font\set font" --cancel-label "Back" \
           --default-item $DEFAULT_NUM \
           --menu "Select font" 0 0 10 $list)
         if [ $? == 0 ]; then
           listnr=1
           for NAME in $(ls /app/kbd/current/share/consolefonts); do
             case $NAME in
               README*)
                  ;;
               *) if [ $listnr = $cmd ]; then
                    NEW_FONT="$NAME"
                  fi
                  listnr=$(($listnr+1))
                  ;;
             esac
           done
         fi
         ;;
      4) list=""
         listnr=1
         for DIRDIR in qwerty qwertz azerty; do
           for NAME in $(ls /app/kbd/current/share/keymaps/i386/$DIRDIR); do
             list="$list $listnr $DIRDIR/$NAME"
             if [ "$NEW_KEYB" == "$DIRDIR/$NAME" ]; then
               DEFAULT_NUM=$listnr
             fi
             listnr=$(($listnr+1))
           done
         done
         cmd=$(dialog --stdout --backtitle "$PROMPT\keyboard and font\set keyboard" --cancel-label "Back" \
                 --default-item $DEFAULT_NUM \
                 --menu "Select keyboard" 0 0 10 $list)
         listnr=1
         for DIRDIR in qwerty qwertz azerty; do
           for NAME in $(ls /app/kbd/current/share/keymaps/i386/$DIRDIR); do
             if [ $listnr = $cmd ]; then
               NEW_KEYB="$DIRDIR/$NAME"
             fi
             listnr=$(($listnr+1))
           done
         done
         ;;
      5) if [ "$1" = "" ]; then
           change_value_in_conf_file "FONT" "$NEW_FONT"
           change_value_in_conf_file "KEYB" "$NEW_KEYB"
           FONT=$NEW_FONT
           KEYB=$NEW_KEYB
         else
           change_value_in_conf_file "$1_FONT" "$NEW_FONT"
           change_value_in_conf_file "$1_KEYB" "$NEW_KEYB"
         fi
         break;
         ;;
      esac
    else
      break;
    fi
  done
  /app/kbd/current/bin/setfont -C /dev/tty1 $FONT
  /app/kbd/current/bin/loadkeys /app/kbd/current/share/keymaps/i386/$KEYB
}

set_time_zone() {
  list=""
  listnr=1
  for NAME in $(ls /app/tzdb/current/usr/share/zoneinfo); do
    if [ -d "/app/tzdb/current/usr/share/zoneinfo/$NAME" ]; then
      for NAME2 in $(ls /app/tzdb/current/usr/share/zoneinfo/$NAME); do
        list="$list $listnr $NAME/$NAME2"
        if [ "$TIMEZONE" == "$NAME/$NAME2" ]; then
          DEFAULT_NUM=$listnr
        fi
        listnr=$(($listnr+1))
      done
    else
      list="$list $listnr $NAME"
      if [ "$TIMEZONE" == "$NAME" ]; then
        DEFAULT_NUM=$listnr
      fi
      listnr=$(($listnr+1))
    fi
  done
  cmd=$(dialog --stdout --backtitle "PLLinux\set timezone" --cancel-label "Back" \
           --default-item $DEFAULT_NUM \
           --menu "Selected timezone $TIMEZONE. Please select new value" 0 0 10 $list)
  if [ $? = 0 ]; then
    listnr=1
    for NAME in $(ls /app/tzdb/current/usr/share/zoneinfo); do
      if [ -d "/app/tzdb/current/usr/share/zoneinfo/$NAME" ]; then
        for NAME2 in $(ls /app/tzdb/current/usr/share/zoneinfo/$NAME); do
          if [ $listnr = $cmd ]; then
            TIMEZONE=$NAME/$NAME2
            change_value_in_conf_file "TIMEZONE" "$TIMEZONE"
          fi
          listnr=$(($listnr+1))
        done
      else
        if [ $listnr = $cmd ]; then
          TIMEZONE=$NAME
          change_value_in_conf_file "TIMEZONE" "$TIMEZONE"
        fi
        listnr=$(($listnr+1))
      fi
    done
  fi
}

add_new_user() {
  cmd=$(dialog --stdout --backtitle "PLLinux\set users\add new user" --cancel-label "Back" \
           --menu "Add new user" 0 0 10 1 "x")
}

find_app_description() {
  fl=1
  if [ -e "$1/readme.md" ]; then
     sectionDescription=0
     while read -r line; do
       if [ "$line" = "**Description**" ]; then
         sectionDescription=1
       elif [ "$line" = "" ]; then
         sectionDescription=0;
       elif [ "$sectionDescription" = 1 ]; then
         if [ "$APP_DESC" == "" ]; then
           if [ "$fl" = "1" ]; then
             case $line in
             *\"*) ;;
             *)
               echo \"$line\"
               ;;
             esac
             fl=0
           fi
         fi
       fi
     done < $1/readme.md
  fi
  if [ "$fl" = "1" ]; then
    echo \"\"
  fi
}

all_apps() {
  listnr=1
  for APP_NAME in $(ls ${DIR}app); do
    for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
      if [ "$APP_VERSION" == "current" ]; then
        echo  "$listnr "
        echo  "${APP_NAME}:${APP_VERSION} "
        case $USER_APPS in
        *${APP_NAME}\ ${APP_VERSION}*)
          echo  "on "
          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
          ;;
        *)
          echo  "off "
          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
          ;;
        esac
        listnr=$(($listnr+1))
      fi
    done
  done
  for APP_NAME in $(ls ${DIR}app); do
    for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
      if [ "$APP_VERSION" != "current" ]; then
        echo  "$listnr "
        echo  "${APP_NAME}:${APP_VERSION} "
        case $USER_APPS in
        *${APP_NAME}\ ${APP_VERSION}*)
          echo  "on "
          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
          ;;
        *)
          echo  "off "
          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
          ;;
        esac
        listnr=$(($listnr+1))
      fi
    done
  done
}

set_existing_user_apps() {
  get_value_from_conf_file "$1_APPS"
  USER_APPS="$CONF_FILE_VALUE"

  abc=$( echo dialog --stdout --backtitle \"PLLinux\\set users\\$1\\available apps\" --cancel-label "Back" \
         --visit-items --item-help   \
         --buildlist \"Set apps for $1 - non available on left, available on right\" 0 0 10 $(all_apps))
  cmd=$(eval $abc)

  if [ $? = 0 ]; then
    list=""
    listnr=1
    cmd=" $cmd "
    for APP_NAME in $(ls ${DIR}app); do
      for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
        if [ "$APP_VERSION" == "current" ]; then
          case $cmd in
          *\ $listnr\ *)
            if [ "$list" != "" ]; then
              list="${list}:"
            fi
            list="${list}${APP_NAME} ${APP_VERSION}"
          esac
          listnr=$(($listnr+1))
        fi
      done
    done
    for APP_NAME in $(ls ${DIR}app); do
      for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
        if [ "$APP_VERSION" != "current" ]; then
          case $cmd in
          *\ $listnr\ *)
            if [ "$list" != "" ]; then
              list="${list}:"
            fi
            list="${list}${APP_NAME} ${APP_VERSION}"
          esac
          listnr=$(($listnr+1))
        fi
      done
    done
    change_value_in_conf_file "$1_APPS" "$list"
  fi
}

set_existing_user_features() {
  get_value_from_conf_file "$1_FEATURES"
  USER_FEATURES="$CONF_FILE_VALUE"
  case $USER_FEATURES in
    *\ network*) USER_NETWORK="x on" ;; *) USER_NETWORK="- off" ;;
  esac
  case $USER_FEATURES in
    *\ proc*) USER_PROCESSES="x on" ;; *) USER_PROCESSES="- off" ;;
  esac
  case $USER_FEATURES in
    *\ processesall*) USER_ALL_PROCESSES="x on" ;; *) USER_ALL_PROCESSES="- off" ;;
  esac
  case $USER_FEATURES in
    *\ mnt*) USER_MNT="x on" ;; *) USER_MNT="- off" ;;
  esac
  case $USER_FEATURES in
    *\ reset*) USER_RESET="x on" ;; *) USER_RESET="- off" ;;
  esac

  cmd=$(dialog --stdout --backtitle "PLLinux\set users\\$1\features" --cancel-label "Back" \
         --checklist "Set features for $1, \"x\" shows previous setup" 0 0 10 \
                   "Access to allprocesses (from all users)" $USER_ALL_PROCESSES \
                   "Access to /mnt"                          $USER_MNT \
                   "Access to /proc"                         $USER_PROCESSES \
                   "Access to the network"                   $USER_NETWORK \
                   "System reset and shutdown"               $USER_RESET)

  if [ $? = 0 ]; then
    USER_FEATURES="";
    for FEATFEAT in proc processesall mnt network reset; do
      case $cmd in
        *$FEATFEAT*) USER_FEATURES="$USER_FEATURES $FEATFEAT" ;;
      esac
    done
    change_value_in_conf_file "$1_FEATURES" "$USER_FEATURES"
  fi
}

set_existing_user_password() {
  IFS=$IFSORIG
  if [ ! "$DIR" = "/" ]; then
      dialog --backtitle "PLLinux\set users\\$1\password" \
        --msgbox "Not possible in host system." 10 30
  else
    clear
    passwd $1
    echo "Press any key to continue..."
    read
  fi
}

set_existing_user() {
  while true; do
    cmd=$(dialog --stdout --backtitle "PLLinux\set users\\$1" --cancel-label "Back" \
           --menu "Set user $1" 0 0 6 1 "Apps available to the user" \
                   2 "App language (todo)" \
                   3 "Background scheduled tasks setup by this user" \
                   4 "Features" \
                   5 "Keyboard and font" \
                   6 "Password" )
    if [ $? == 0 ]; then
      case $cmd in
        1) set_existing_user_apps $1 ;;
        3) tasks "$1" ;;
        4) set_existing_user_features $1 ;;
        5) get_value_from_conf_file "$1_KEYB"
           NEW_KEYB="$CONF_FILE_VALUE"
           if [ "$NEW_KEYB" = "" ]; then
             NEW_KEYB="$KEYB"
           fi
           get_value_from_conf_file "$1_FONT"
           NEW_FONT="$CONF_FILE_VALUE"
           if [ "$NEW_FONT" = "" ]; then
             NEW_FONT="$FONT"
           fi
           set_keyboard_font_general_or_user $1 ;;
        6) set_existing_user_password $1 ;;
      esac
    else
      break
    fi
  done
}

set_users() {
  while true; do
    listnr=1
    list=""
    while read -r line; do
      IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
      list="$list $listnr $USER_NAME"
      listnr=$(($listnr+1))
    done < "${DIR}etc/passwd"
    list="$list $listnr Add(todo)"
    listnr=$(($listnr+1))
    list="$list $listnr Delete(todo)"
    cmd=$(dialog --stdout --backtitle "PLLinux\set users" --cancel-label "Back" \
           --menu "Set users" 0 0 10 $list)
    if [ $? == 0 ]; then
      USRUSR=""
      listnr=1
      while read -r line; do
        IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
        if [ $listnr = $cmd ]; then
          USRUSR="$USER_NAME"
          break;
        fi
        listnr=$(($listnr+1))
      done < "${DIR}etc/passwd"
      if [ "$USRUSR" = "" ]; then
        add_new_user
      else
        set_existing_user $USRUSR
      fi
    else
      break;
    fi
  done
}

format_install2() {
  dialog --yesno "Really? This is LAST WARNING. $1 will be cleaned from previous data. THIS CANNOT BE REVERSED" 20 40
    if [ $? == 0 ]; then
      clear

      mkfs -V -t ext4 $1

      mkdir /mnt/install
      /app/util-linux/current/bin/mount -t ext4 -o rw,noatime,nodiratime,sync $1 /mnt/install

      cd /mnt/install

      for folderentry in app bin dev etc home mnt proc run sys tmp lib64 log log/tmp; do mkdir $folderentry; done

      /app/rsync/current/bin/rsync -a --info=progress2 /etc/ etc

      echo "Copying /app. This will need some time (even 20-30 seconds or more)"
      /app/rsync/current/bin/rsync -a --info=progress2 /app/ app

      for userentry in root user user2; do 
        case $userentry in
          root) GRP=0 ;;
          user) GRP=1000 ;;
          user2) GRP=1001 ;;
        esac

        for direntry in home/$userentry home/$userentry/app home/$userentry/files; do
          sudo mkdir $direntry
          sudo chown $GRP $direntry
          sudo chgrp $GRP $direntry
        done

        sudo chmod u+rwx home/$userentry
        sudo chmod g-rwx home/$userentry
        sudo chmod o-rwx home/$userentry
      done

      if [ ! -d "etc." ]; then ln -s etc etc.; fi
      if [ ! -d "other" ]; then ln -s home/root other; fi

      cd bin
      ln -s /sh sh
      ln -s /app/bash/current/bin/bash bash
      cd ..

      cd lib64
      ln -s /app/glibc/current/lib/ld-linux-x86-64.so.2 ld-linux-x86-64.so.2
      chmod a+x ld-linux-x86-64.so.2
      cd ..

      /app/busybox/current/bin/umount -f .mnt/install
      rmdir /mnt/install

      UUID=$(/app/busybox/current/sbin/blkid | grep $1)
      for PAR in $UUID; do
        case $PAR in
        *UUID*)
          ROOT_DEVICE_ID=${PAR#UUID=\"}
          ROOT_DEVICE_ID=${ROOT_DEVICE_ID%\"}
          ;;
        esac
      done

      echo '#!/bin/sh' > /tmp/42_custom
      echo 'exec tail -n +3 $0' >> /tmp/42_custom
      echo menuentry 'PLLINUX2' --class ubuntu --class gnu-linux --class gnu --class os \$menuentry_id_option 'PL22' { >> /tmp/42_custom
      echo set root='hd1,gpt1' >> /tmp/42_custom
      echo   echo 'Loading PLLINUX ...' >> tmp/42_custom
      echo   linux /app/kernel/current/bzImage root=UUID=$ROOT_DEVICE_ID rw >> /tmp/42_custom
      echo   initrd /app/initramfs/current/initramfs.gz >> /tmp/42_custom
      echo } >> /tmp/42_custom

      chmod a+x /tmp/42_custom

      echo System cloned into $1 partition. Example GRUB file for starting it saved in the /tmp/42_custom file.
      read x
    fi
}

format_install() {
  dialog --yesno "Do you want to format and use partition $1 for new installation? THIS CANNOT BE REVERSED" 20 40
  if [ $? == 0 ]; then
    format_install2 $1
  fi
}

process_one_disk_list() {
    if [ "$2" != "1" ]; then
      return
    fi
    disks=$(parted -l -m 2> /dev/null)
    thisdisk=0
    list=""
    listnr=3
    while read -r line; do
      if [ "$thisdisk" = "0" ]; then
        case $line in
          $1*) thisdisk=1
        esac
      else
        if [ "$line" = "" ]; then
          thisdisk=0
        else
          IFS=":" read -r PART_NUMER PART_START PART_END PART_SIZE PART_SYSTEM PART_OTHER PART_FLAGS << EOF
$line
EOF
          echo $list
          echo $listnr
          if [ "$PART_FLAGS" != ";" ]; then
            PART_FLAGS=" $PART_FLAGS"
          else
            PART_FLAGS=""
          fi
          echo \"Partition $(($listnr-2)) \(${PART_SIZE}, ${PART_SYSTEM}${PART_FLAGS}\) - format to ext4 and copy PLLinux there\"
          listnr=$(($listnr+1))
        fi
      fi
    done <<< "$disks"
}

process_one_disk() {
  while true; do
    disks=$(parted -l -m 2> /dev/null)
    thisdisk=0
    list=""
    listnr=1
    if [ "$2" = "1" ]; then
      while read -r line; do
        if [ "$thisdisk" = "0" ]; then
          case $line in
            $1*) thisdisk=1
          esac
        else
          if [ "$line" = "" ]; then
            thisdisk=0
          else
            listnr=$(($listnr+1))
          fi
        fi
      done <<< "$disks"
    fi
    abc=$(echo dialog --stdout --backtitle \"PLLinux/install to other disk/device $1\" --cancel-label "Back" \
           --menu \"Disk $1\" 0 0 6 \
           1 \"Partition disk \(cfdisk\)\" \
                     2 \"SMART disk info \(smartctl\)\" \
           $(process_one_disk_list $1 $2) )
    cmd=$(eval $abc)
    if [ $? == 0 ]; then
      if [ "$cmd" = "1" ]; then
        cfdisk $1
      elif [ "$cmd" = "2" ]; then
        dialog --msgbox "$(smartctl -a $1)" 100 100
      else
        format_install $1p$(($cmd-2))
      fi
    else
      break
    fi
  done
}

install_to() {
  defnum=1
  while true; do
    disks=$(parted -l -m 2> /dev/null | grep /dev)
    if [ "$disks" = "" ]; then
      dialog --backtitle "PLLinux\install to other partition" \
        --msgbox "No disks detected. Looks like running from mc sandbox or lack of rights/permissions." 10 30
      return
    fi
    listnr=1
    list=""
    while read -r line; do
      IFS=":" read -r DEV_NAME OTHER << EOF
$line
EOF
      list="$list $listnr $DEV_NAME "
      listnr=$(($listnr+1))
    done <<< "$disks"
    cmd=$(dialog --stdout --backtitle "PLLinux\install to other disk" --cancel-label "Back" \
           --default-item $defnum \
           --menu "Install PLLinux to other partition or disk" 0 0 6 $list )
    if [ $? == 0 ]; then
        listnr=1
        list=""
        DEVDEV=""
        while read -r line; do
          IFS=":" read -r DEV_NAME OTHER << EOF
$line
EOF
          if [ "$listnr" == "$cmd" ]; then
            DEVDEV=$DEV_NAME
            defnum=$listnr
          fi
          listnr=$(($listnr+1))
        done <<< "$disks"
        # this must be called after while
        process_one_disk $DEVDEV $1
    else
      break
    fi
  done
}

task_schedule() {
  while true; do
    cmd=$(dialog --stdout --backtitle "$PROMPT\\task schedule" --cancel-label "Back" \
      --form "Pls provide values, you can put intervals or separate values with comma, star means no setup, spaces will be deleted" 0 0 8 \
      "Minute (1-59)" 1 1 "$SMINUTE" 1 20 15 0 \
      "Hour (0-23)" 2 1 "$SHOUR" 2 20 15 0 \
      "Month day (1-31)" 3 1 "$SDAY" 3 20 15 0 \
      "Month (1-12)" 4 1 "$SMONTH" 4 20 15 0 \
      "Day of week (0-6)" 5 1 "$SDOW" 5 20 15 0 )
    if [ $? == 0 ]; then
      linenr=1
      while read -r line; do
        case $linenr in
        1) SMINUTE="$line" ;;
        2) SHOUR="$line" ;;
        3) SDAY="$line" ;;
        4) SMONTH="$line" ;;
        5) SDOW="$line" ;;
        esac
        linenr=$(($linenr+1))
        STASK=1
      done <<< "$cmd"
      TASKSTEPNR=$(($TASKSTEPNR+1))
    else
      TASKSTEPNR=$(($TASKSTEPNR-1))
    fi
    break;
  done
}

task_user() {
  listnr=1
  list=""
  defnum=1
  while read -r line; do
    IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
    list="$list $listnr $USER_NAME"
    if [ "$USER_NAME" = "$SUSER" ]; then
      defnum=$listnr
    fi
    listnr=$(($listnr+1))
  done < "${DIR}etc/passwd"

  cmd=$(dialog --stdout --backtitle "$PROMPT\\task user" --cancel-label "Prev" \
       --default-item $defnum \
       --menu "User starting task" 0 0 8 \
       $list )

  if [ $? == 0 ]; then
      TASKSTEPNR=$(($TASKSTEPNR+1))

    listnr=1
    while read -r line; do
      IFS=":" read -r USER_NAME OTHER << EOF
$line
EOF
      if [ "$cmd" = "$listnr" ]; then
        SUSER="$USER_NAME"
      fi
      listnr=$(($listnr+1))
    done < "${DIR}etc/passwd"
  else
    TASKSTEPNR=$(($TASKSTEPNR-1))
  fi
}

task_command() {
  while true; do
    cmd=$(dialog --stdout --backtitle "$PROMPT\\task command" --cancel-label "Prev" \
      --inputbox "Pls enter command (cannot be empty)" 15 100 "$SCMD" )
    if [ $? == 0 ]; then
      if [ "$cmd" == "" ]; then
        continue;
      fi
      TASKSTEPNR=$(($TASKSTEPNR+1))
      SCMD="$cmd"
    else
      TASKSTEPNR=$(($TASKSTEPNR-1))
    fi
    break;
  done
}

task_type() {
  cmd=$(dialog --stdout --backtitle "$PROMPT\\task type" --cancel-label "Prev" \
           --default-item $SSETUPBYSYSTEM \
           --menu "Task type" 0 0 6 1 "Setup by root (saved in crontab)" \
                   2 "Setup by user itself (saved in user editable file)"  )
  if [ $? == 0 ]; then
    SSETUPBYSYSTEM="$cmd"
    TASKSTEPNR=$(($TASKSTEPNR+1))
  else
    TASKSTEPNR=$(($TASKSTEPNR-1))
  fi
}

tasks_list() {
  listnr=1
  IFS=" "
  for task_fn in $TASK_FILE_LIST; do
    while read -r line; do
      if [ "$task_fn" = "crontab" ]; then
        IFS=" " read -r TASK_MIN TASK_HOUR TASK_DOM TASK_MONTH TASK_DOW TASK_USR TASK_COMMAND << EOF
$line
EOF
      else
        IFS=" " read -r TASK_MIN TASK_HOUR TASK_DOM TASK_MONTH TASK_DOW TASK_COMMAND << EOF
$line
EOF
        TASK_USR="$task_fn"
      fi
      SCHEDULE=""
      IFS=","
      if [ "${TASK_DOW}" != "*" ]; then
        for PERIOD in "$TASK_DOW"; do
          case $PERIOD in
          0) SCHEDULE="$SCHEDULE every Mon" ;;
          1) SCHEDULE="$SCHEDULE every Tue" ;;
          2) SCHEDULE="$SCHEDULE every Wed" ;;
          3) SCHEDULE="$SCHEDULE every Thu" ;;
          4) SCHEDULE="$SCHEDULE every Fri" ;;
          5) SCHEDULE="$SCHEDULE every Sat" ;;
          6) SCHEDULE="$SCHEDULE every Sun" ;;
          esac
        done
      else
        SCHEDULE="$SCHEDULE every week day"
      fi
      if [ "${TASK_DOM}" != "*" ]; then
        for PERIOD in "$TASK_DOM"; do
          if [ "$PERIOD" != "*" ]; then
            if [ "${TASK_MONTH}" != "*" ]; then
              for PERIOD2 in "$TASK_MONTH"; do
                case $PERIOD2 in
                1) SCHEDULE="$SCHEDULE $PERIOD Jan" ;;
                2) SCHEDULE="$SCHEDULE $PERIOD Feb" ;;
                3) SCHEDULE="$SCHEDULE $PERIOD Mar" ;;
                4) SCHEDULE="$SCHEDULE $PERIOD Apr" ;;
                5) SCHEDULE="$SCHEDULE $PERIOD May" ;;
                6) SCHEDULE="$SCHEDULE $PERIOD Jun" ;;
                7) SCHEDULE="$SCHEDULE $PERIOD Jul" ;;
                8) SCHEDULE="$SCHEDULE $PERIOD Aug" ;;
                9) SCHEDULE="$SCHEDULE $PERIOD Sep" ;;
                10) SCHEDULE="$SCHEDULE $PERIOD Oct" ;;
                11) SCHEDULE="$SCHEDULE $PERIOD Nov" ;;
                12) SCHEDULE="$SCHEDULE $PERIOD Dec" ;;
                esac
              done
            else
              SCHEDULE="$SCHEDULE every month day $PERIOD"
            fi
          fi
        done
      else
        SCHEDULE="$SCHEDULE every month day"
      fi
      if [ "${TASK_HOUR}" != "*" ]; then
        for PERIOD in ${TASK_HOUR}; do
          if [ "$PERIOD" != "*" ]; then
            SCHEDULE="${SCHEDULE} hour ${PERIOD}"
            if [ "${TASK_MIN}" != "*" ]; then
              for PERIOD2 in "${TASK_MIN}"; do
                if [ "$PERIOD2" != "*" ]; then
                   SCHEDULE="${SCHEDULE}:${PERIOD2}"
                fi
              done
            else
              SCHEDULE="${SCHEDULE} every min"
            fi
          fi
        done
      else
        if [ "${TASK_MIN}" != "*" ]; then
            for PERIOD2 in "${TASK_MIN}"; do
              if [ "$PERIOD2" != "*" ]; then
                 SCHEDULE="${SCHEDULE} every hour min ${PERIOD2}"
              fi
            done
        fi
      fi
      if [ "${SCHEDULE}" == "" ]; then
        SCHEDULE=" every min of every day"
      fi
      SCHEDULE="${SCHEDULE/every week day every month day/every day}"
      IFS=" "
      echo "$listnr "
      SETUP="($TASK_USR) "
      echo \"$SETUP ${SCHEDULE:1} - $TASK_COMMAND\"
      listnr=$(($listnr+1))
    done < "${DIR}etc/$task_fn"
  done
  IFS=$IFSORIG
  echo " $listnr "
  echo "Add"
  echo " $(($listnr+1)) "
  echo "Delete"
}

tasks_file_list() {
  if [ "$1" = "crontab" ]; then
    TASK_FILE_LIST="crontab"
    for filename in $(cd ${DIR}etc/crond.d && ls *); do
      TASK_FILE_LIST="$TASK_FILE_LIST crond.d/$filename"
    done
  else
    TASK_FILE_LIST="crond.d/$1"
  fi
}

tasks_list_num() {
  listnr=1
  IFS=" "
  for task_fn in $TASK_FILE_LIST; do
    while read -r line; do
      listnr=$(($listnr+1))
    done < "${DIR}etc/$task_fn"
  done
  IFS=$IFSORIG
  echo " $listnr "
  echo "Add\(todo\)"
}

tasks() {
  listnr3=1
  tasks_file_list $1
  while true; do
  if [ "$1" = "crontab" ]; then
    PROMPT="PLLinux";
    PROMPT2="";
  else
    PROMPT="PLLinux\set users\\$1";
    PROMPT2=" for $1";
  fi
  PROMPT="$PROMPT\\background tasks scheduler"
  abc=$(echo dialog --stdout --backtitle \"$PROMPT\" --cancel-label "Back" \
           --default-item $listnr3 \
       --menu \"Commands run$PROMPT2 in the background in the specified time\" 0 0 8 \
       $(tasks_list) )
  cmd=$(eval $abc)
  if [ $? == 0 ]; then
    tasks_list_num $1
    listnr3=$cmd
    case $cmd in
    $listnr)
        PROMPT="$PROMPT\\new task"
        SMINUTE="*"
        SHOUR="*"
        SDAY="*"
        SMONTH="*"
        SDOW="*"
        SUSER="root"
        SCMD=""
        SSETUPBYSYSTEM=2
        TASKSTEPNR=1
        while true; do
          case $TASKSTEPNR in
          0) break ;;
          1) task_schedule $listnr $1 ;;
          2) task_command ;;
          3) if [ "$1" != "crontab" ]; then
               TASKSTEPNR=5
             else
               task_user
             fi ;;
          4) task_type ;;
          5) if [ "$SSETUPBYSYSTEM" = "1" ]; then
               echo "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SUSER $SCMD" >> ${DIR}etc/crontab
               listnr=1
               for task_fn in $TASK_FILE_LIST; do
                 while read -r line; do
                   if [ "$task_fn" = "crontab" ] && [ "$line" = "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SUSER $SCMD" ]; then
                     listnr3=$listnr
                   fi
                   listnr=$(($listnr+1))
                 done < "${DIR}etc/crontab"
               done
             else
               echo "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SCMD" >> ${DIR}etc/crond.d/$SUSER
               listnr=1
               for task_fn in $TASK_FILE_LIST; do
                 while read -r line; do
                   if [ "$task_fn" = "crond.d/$SUSER" ] && [ "$line" = "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SCMD" ]; then
                     listnr3=$listnr
                   fi
                   listnr=$(($listnr+1))
                 done < "${DIR}etc/$task_fn"
               done
             fi
             break
          esac
        done
        ;;
    $(($listnr+1)) )
        ;;
    *)
        PROMPT="$PROMPT\\edit task"
        listnr=1
        for task_fn in $TASK_FILE_LIST; do
          while read -r line; do
            if [ "$task_fn" = "crontab" ]; then
              IFS=" " read -r TASK_MIN TASK_HOUR TASK_DOM TASK_MONTH TASK_DOW TASK_USR TASK_COMMAND << EOF
$line
EOF
            else
              IFS=" " read -r TASK_MIN TASK_HOUR TASK_DOM TASK_MONTH TASK_DOW TASK_COMMAND << EOF
$line
EOF
              TASK_USR="${task_fn#*/}"
            fi
            if [ "$listnr" = "$cmd" ]; then
              if [ "$task_fn" = "crontab" ]; then
                SSETUPBYSYSTEM=1
              else
                SSETUPBYSYSTEM=2
              fi
              SMINUTE="$TASK_MIN"
              SHOUR="$TASK_HOUR"
              SDAY="$TASK_DOM"
              SMONTH="$TASK_MONTH"
              SDOW="$TASK_DOW"
              SUSER="$TASK_USR"
              SCMD="$TASK_COMMAND"
            fi
            listnr=$(($listnr+1))
          done < "${DIR}etc/$task_fn"
done
          TASKSTEPNR=1
          while true; do
            case $TASKSTEPNR in
            0) break ;;
            1) task_schedule $listnr3 ;;
            2) task_command ;;
            3) if [ "$1" != "crontab" ]; then
                 TASKSTEPNR=5
               else
                 task_user
               fi ;;
            4) task_type ;;
            5) listnr2=1
#fixme: position during changing type
               for task_fn in $TASK_FILE_LIST; do
                 file_content=$(cat ${DIR}etc/$task_fn)
                 echo -n "" > ${DIR}etc/$task_fn
                 while IFS= read -r line; do
                   if [ "$listnr2" != "$listnr3" ]; then
                     echo "$line" >> ${DIR}etc/$task_fn
                   else
                     if [ "$task_fn" = "crontab" ]; then
                       echo "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SUSER $SCMD" >> ${DIR}etc/crontab
                     else
                       echo "$SMINUTE $SHOUR $SDAY $SMONTH $SDOW $SCMD" >> ${DIR}etc/$task_fn
                     fi
                   fi
                   listnr2=$(($listnr2+1))
                 done <<< "$file_content"
               done
               break
            esac
          done
          ;;
    esac
  else
    break;
  fi
  done
}

log_feature_type() {
  list=""
  for TYPE in   kern user mail daemon auth syslog lpr news uucp cron authpriv ftp ntp security console priority; do
    case $LOG_TYPE in
    *$TYPE*)
      list="$list $TYPE x on ";
      ;;
    *)
      list="$list $TYPE - off ";
      ;;
    esac
  done
  cmd=$(dialog --stdout --backtitle "PLLinux\set users\\$1\features" --cancel-label "Back" \
         --checklist "Set features for $1, \"x\" shows previous setup" 0 0 10 $list)
  if [ $? == 0 ]; then
    LOG_TYPE=""
    for TYPE in   kern user mail daemon auth syslog lpr news uucp cron authpriv ftp ntp security console priority; do
      case $cmd in
      *$TYPE*)
         if [ "$LOG_TYPE" != "" ]; then LOG_TYPE="$LOG_TYPE,"; fi
         LOG_TYPE="$LOG_TYPE$TYPE";
       ;;
      esac
    done
    TASKSTEPNR=$(($TASKSTEPNR+1))
  else
    TASKSTEPNR=$(($TASKSTEPNR-1))
  fi
}

log_feature_priority() {
  list=""
  for TYPE in   emerg alert crit err warning notice info debug; do
    case $LOG_PRIORITY in
    *$TYPE*)
      list="$list $TYPE x on ";
      ;;
    *)
      list="$list $TYPE - off ";
      ;;
    esac
  done
  cmd=$(dialog --stdout --backtitle "PLLinux\set users\\$1\features" --cancel-label "Back" \
         --checklist "Priorities are sorted from the most (top) to least important (bottom)" 0 0 10 $list)
  if [ $? == 0 ]; then
    LOG_PRIORITY=""
    for TYPE in   emerg alert crit err warning notice info debug; do
      case $cmd in
      *$TYPE*)
         if [ "$LOG_PRIORITY" != "" ]; then LOG_PRIORITY="$LOG_PRIORITY,"; fi
         LOG_PRIORITY="$LOG_PRIORITY$TYPE";
       ;;
      esac
    done
    TASKSTEPNR=$(($TASKSTEPNR+1))
  else
    TASKSTEPNR=$(($TASKSTEPNR-1))
  fi
}

log_file() {
  while true; do
    cmd=$(dialog --stdout --backtitle "$PROMPT\\task command" --cancel-label "Prev" \
      --inputbox "Pls enter command (cannot be empty)" 15 100 "${LOG_FILE}" )
    if [ $? == 0 ]; then
      if [ "$cmd" == "" ]; then
        continue;
      fi
      TASKSTEPNR=$(($TASKSTEPNR+1))
      LOG_FILE="$cmd"
    else
      TASKSTEPNR=$(($TASKSTEPNR-1))
    fi
    break;
  done
}

log_entry_list() {
  echo " 1 "
  echo \"Search file\"

  echo " 2 "
  echo \"Save and back\"

  listnr=3
  IFS=";"
    while read -r entry; do
      SCHEDULE=""
      echo "$listnr "
      echo \"Rule - ${entry}\"
      listnr=$(($listnr+1))
    done <<< "$1"
  IFS=$IFSORIG

  echo " $listnr "
  echo \"File - $2\"

  echo " $(($listnr+1)) "
  echo \"Clear file\"

  echo " $(($listnr+2)) "
  echo \"Delete rule\"

  echo " $(($listnr+3)) "
  echo \"Delete all\"
}

log_entry() {
  INPUT1="$1"
  INPUT2="$2"
  while true; do
    PROMPT="PLLinux\\logs"
    abc=$(echo dialog --stdout --backtitle \"$PROMPT\" --cancel-label "Back" \
           --default-item $listnr3 \
       --menu \"Logs saved to files \(temporary or permanent\)\" 0 0 8 \
       $(log_entry_list $INPUT1 $INPUT2) )
    cmd=$(eval $abc)
    if [ $? == 0 ]; then
      listnr=1
      IFS=" "
    while read -r entry; do
      listnr=$(($listnr+1))
    done <<< "$INPUT1"
      IFS=$IFSORIG
      case $cmd in
      1 )  #search
        cat $INPUT2 | less # it seems, that msgbox and other dialog elements have size limit
        ;;
      2 )  #save and back
        break
        ;;
      $listnr) # file
        LOG_FILE="$INPUT2"
        log_file ;;
      $(($listnr+3)) )  #clear
        ;;
      $(($listnr+4)) )  #delete rule
        ;;
      $(($listnr+5)) )  #delete all
        ;;
      *) # edit rule
        listnr3=1
        IFS=" "
        while read -r entry; do
          if [ "$cmd" = "$listnr3" ]; then
             break;
          fi
          listnr3=$(($listnr3+1))
        done <<< "$INPUT1"
        IFS=$IFSORIG
        IFS="." read -r LOG_TYPE LOG_PRIORITY << EOF
$line
EOF
        TASKSTEPNR=1
        while true; do
          case $TASKSTEPNR in
          0) break; ;;
          1) log_feature_type ;;
          2) log_feature_priority ;;
          3) 
             NEWFEAT=""
             listnr=1
             IFS=" "
             while read -r entry; do
               if [ "$listnr3" = "$listnr" ]; then
                  NEWFEAT="$NEWFEAT,${LOG_TYPE}.${LOG_PRIORITY}"
               else
                  NEWFEAT="$NEWFEAT,$entry"
               fi
               listnr=$(($listnr+1))
             done <<< "$INPUT1"
             $INPUT1=${NEWFEAT}
             IFS=$IFSORIG

#echo "${LOG_TYPE}.${LOG_PRIORITY} ${LOG_FILE} " >> ${DIR}etc/syslog.conf
# fixme reload service
             break;;
          esac
        done
        ;;
      esac
    else
      break;
    fi
  done
}

log_list() {
  listnr=1
  IFS=" "
    while read -r line; do
        IFS=" " read -r LOG_RULES LOG_FILE << EOF
$line
EOF
      SCHEDULE=""
      IFS=";"
      for RULE in "$LOG_RULES"; do
          case $TYPE in
            kern) SCHEDULE="$SCHEDULE kernel msg" ;;
            user) SCHEDULE="$SCHEDULE user msg" ;;
            mail) SCHEDULE="$SCHEDULE mail msg" ;;
            daemon) SCHEDULE="$SCHEDULE daemon/services msg" ;;
            auth) SCHEDULE="$SCHEDULE authentication msg" ;;
            syslog) SCHEDULE="$SCHEDULE authentication msg" ;;
          esac
      done
      IFS=" "
      echo "$listnr "
      echo \"${LOG_RULES} ${LOG_FILE} size 0KB\"
      listnr=$(($listnr+1))
    done < "${DIR}etc/syslog.conf"

  IFS=$IFSORIG
  echo " $listnr "
  echo "Add"
}

logs() {
  listnr3=1
  while true; do
    PROMPT="PLLinux\\logs"
    abc=$(echo dialog --stdout --backtitle \"$PROMPT\" --cancel-label "Back" \
           --default-item $listnr3 \
       --menu \"Logs saved to files \(temporary or permanent\). Managed by syslogd service\" 0 0 8 \
       $(log_list) )
    cmd=$(eval $abc)
    if [ $? == 0 ]; then

      listnr=1
      IFS=" "
      while read -r line; do
        listnr=$(($listnr+1))
      done < "${DIR}etc/syslog.conf"
      IFS=$IFSORIG

      case $cmd in
      $listnr) # add
        TASKSTEPNR=1
        while true; do
          case $TASKSTEPNR in
          0) break; ;;
          1) log_feature_type ;;
          2) log_feature_priority ;;
          3) LOG_FILE="/log/tmp/example_log"
             log_file ;;
          4) echo "${LOG_TYPE}.${LOG_PRIORITY} ${LOG_FILE} " >> ${DIR}etc/syslog.conf
# fixme reload service
             break;;
          esac
        done
        ;;
      *) # edit
        listnr=1
        IFS=" "
        while read -r line; do
        IFS=" " read -r LOG_RULES LOG_FILE << EOF
$line
EOF
          if [ "$cmd" = "$listnr" ]; then
            break;
          fi
          listnr=$(($listnr+1))
        done < "${DIR}etc/syslog.conf"
        IFS=$IFSORIG
        log_entry $LOG_RULES $LOG_FILE
        ;;
      esac
    else
      break;
    fi
  done
}

service() {
  while true; do
    cmd=$(dialog --stdout --backtitle "PLLinux\background services\\$1" --cancel-label "Back" \
       --menu "Welcome to the PLLinux configuration" 0 0 8 \
       1 stop 2 start 3 restart )
    if [ $? = 0 ]; then
      case $cmd in
      1) cmd2=$(dinitctl stop $1)
         dialog --msgbox "$cmd2" 10 30 ;;
      2) cmd2=$(dinitctl start $1)
         dialog --msgbox "$cmd2" 10 30 ;;
      3) cmd2=$(dinitctl restart $1)
         dialog --msgbox "$cmd2" 10 30 ;;
      esac
    else
      break;
    fi
  done
}

all_services() {
  servicess=$(dinitctl list)
  listnr=1
  while read -r line; do
    IFS=" " read -r SERVICE_NAME X SERVICE_PID << EOF
${line:11}
EOF
    if [ "$SERVICE_NAME" != "boot" ]; then
      DESC="-"
      while read -r line2; do
        case $line2 in
          \#* )
             DESC=$line2 ;;
        esac
        break
      done < "/etc/dinit.d/$SERVICE_NAME"
      echo " $listnr "
      echo \"$SERVICE_NAME - $(dinitctl is-started $SERVICE_NAME) \"
      echo \"$DESC\"
      listnr=$(($listnr+1))
    fi
  done <<< $servicess
}

services() {
  if [ ! -d "/etc/dinit.d" ]; then
    dialog --backtitle "PLLinux\\backgroud services" \
      --msgbox "No services detected. Looks like running from host or lack of rights/permissions." 10 30
    return
  fi
  while true; do
    abc=$(echo dialog --stdout --backtitle \"PLLinux\\background services\" --cancel-label \"Quit\" --item-help \
       --menu \"Services support is provided by dinit package\" 0 0 8 \
       $(all_services))
    cmd=$(eval $abc)
    if [ $? = 0 ]; then
      servicess=$(dinitctl list)
      listnr=1
      while read -r line; do
        IFS=" " read -r SERVICE_NAME X SERVICE_PID << EOF
${line:11}
EOF
        if [ "$SERVICE_NAME" != "boot" ]; then
          if [ "$listnr" = "$cmd" ]; then
             break
          fi
          listnr=$(($listnr+1))
        fi
      done <<< $servicess
      service $SERVICE_NAME
    else
      break;
    fi
  done
}

kernel_param_list() {
  listnr=1
  LISTLIST=$(busybox sysctl -a)
  while read -r line; do
      echo "$listnr "
      echo \"$line\"
      listnr=$(($listnr+1))
  done <<< $LISTLIST
  echo " $listnr "
  echo "Add"
  echo " $(($listnr+1)) "
  echo "Delete"
}

sysctl_kernel_params() {
  listnr3=1
  while true; do
    abc=$(echo dialog --stdout --backtitle \"PLLinux\\kernel params\" --cancel-label "Back" \
       --menu \"Linux kernel paramaters\" 0 0 8 \
       $(kernel_param_list) )
    cmd=$(eval $abc)
    if [ $? == 0 ]; then
      break;
    else
      break;
    fi
  done
}

devices() {
  while true; do
    abc=$(echo dialog --stdout --backtitle \"PLLinux\\device manager\" --cancel-label "Back" --menu \"Welcome to the device manager\" 0 0 9 \
       1 \"CPU \(lscpu\)\" \
       2 \"Disks info and partitioning\" \
       3 \"Monitor info \(read-edid\)\" \
       4 \"Network interfaces \(ip\)\" \
       5 \"PCI \(lspci\)\" \
       6 \"Power options\" \
       7 \"RAM \(decode-dimms\)\" \
       8 \"Sensors \(sensors\)\" \
       9 \"UEFI \(dmidecode\)\")
    cmd=$(eval $abc)
    if [ $? = 0 ]; then
      case $cmd in
      1) dialog --backtitle "PLLinux\device manager\CPU\(lscpu\)" --msgbox "$(lscpu)" 100 90 ;;
      2) install_to 0 ;;
      4) dialog --backtitle "PLLinux\device manager\network interfaces \(ip\)" --msgbox "$(ip link show)" 100 90 ;;
      5) dialog --backtitle "PLLinux\device manager\PCI info \(lspci\)" --msgbox "$(lspci -vvv)" 100 90 ;;
      7) dialog --backtitle "PLLinux\device manager\RAM info \(decode-dimms\)" --msgbox "$(decode-dimms)" 100 90 ;;
      8) dialog --backtitle "PLLinux\device manager\sensors info \(sensors\)" --msgbox "$(sensors)" 100 90 ;;
      9) dialog --backtitle "PLLinux\device manager\UEFI info \(dmidecode\)" --msgbox "$(dmidecode)" 100 90 ;;
      esac
    else
      break;
    fi
  done
}

all_system_apps() {
  listnr=1
#  for APP_NAME in $(ls ${DIR}app); do
#    for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
#      if [ "$APP_VERSION" == "current" ]; then
#        echo  "$listnr "
#        echo  "${APP_NAME}:${APP_VERSION} "
#          echo  "off "
#          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
#        listnr=$(($listnr+1))
#      fi
#    done
#  done
  for APP_NAME in $(ls ${DIR}app); do
    appnum=0
    case $SYSTEM_APPS in
      *${APP_NAME}*)
        for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
          appnum=$(($appnum+1))
        done
      ;;
    esac
    #cannot delete system apps when there is only one version installed
    if [ "$appnum" != 2 ]; then
      for APP_VERSION in $(ls ${DIR}app/${APP_NAME}); do
        if [ "$APP_VERSION" != "current" ]; then
          echo  "$listnr "
          CURRENT=$(realpath ${DIR}app/${APP_NAME}/current)
          if [ "$CURRENT" = "${DIR}app/${APP_NAME}/${APP_VERSION}" ]; then
            echo  \"${APP_NAME}:${APP_VERSION} - current - $(du ${DIR}app/${APP_NAME}/${APP_VERSION} -s -h -c | grep total)\"
          else
            echo  \"${APP_NAME}:${APP_VERSION} - $(du ${DIR}app/${APP_NAME}/${APP_VERSION} -s -h -c | grep total)\"
          fi
          echo  " off "
          echo  $(find_app_description ${DIR}app/${APP_NAME}/${APP_VERSION})
          listnr=$(($listnr+1))
        fi
      done
    fi
  done
}

delete_system_apps() {
  abc=$( echo dialog --stdout --backtitle \"PLLinux\\apps\\delete\" --cancel-label "Back" \
         --visit-items --item-help   \
         --buildlist \"Marking apps for deleting - installed on left, marked for delete on right\" 0 0 10 $(all_system_apps))
  cmd=$(eval $abc)

  if [ $? = 0 ]; then
    list=""
    listnr=1
  fi
}

get_repo_updates() {
  REPO_UPDATES=""
  LINE_NUM=1
  rm -r -f /tmp/apprepo 2> /dev/null
  while read -r repo_line; do
    IFS=" " read -r REPO_URL REPO_FIRST_PUBLIC_KEY REPO_SECOND_PUBLIC_KEY << EOF
$repo_line
EOF
    if [ "${REPO_URL:0:5}" = "https" ]; then
      mkdir /tmp/apprepo 2> /dev/null
      mkdir /tmp/apprepo/${LINE_NUM} 2> /dev/null
      LINK=${REPO_URL/;/:}
#echo "$LINK"
#echo "${LINK/[*]/app.repo.updates}"
      echo -n "Getting repo.updates..."
      wget -O /tmp/apprepo/${LINE_NUM}/app.repo.updates ${LINK/[*]/app.repo.updates} > /dev/null 2> /dev/null
      if [ $? -eq 0 ]; then
        echo -n "getting first key..."
        wget -O /tmp/apprepo/${LINE_NUM}/app.publickey1 $REPO_FIRST_PUBLIC_KEY > /dev/null 2> /dev/null
        if [ $? -eq 0 ]; then
          if [ $REPO_FIRST_PUBLIC_KEY = $REPO_SECOND_PUBLIC_KEY ]; then
            echo "repo $REPO_URL issue - the same public key (worse security)"
            cp /tmp/apprepo/${LINE_NUM}/app.publickey1 /tmp/apprepo/${LINE_NUM}/app.publickey2
          else 
            echo -n "getting second key..."
            wget -O /tmp/apprepo/${LINE_NUM}/app.publickey2 $REPO_SECOND_PUBLIC_KEY > /dev/null 2> /dev/null
          fi
          if cmp -s /tmp/apprepo/${LINE_NUM}/app.publickey1 /tmp/apprepo/${LINE_NUM}/app.publickey2; then
            echo
            while read -r line; do
              REPO_UPDATES="$REPO_UPDATES$line $REPO_URL /tmp/apprepo/${LINE_NUM}/app.publickey1
"
            done < "/tmp/apprepo/${LINE_NUM}/app.repo.updates"
          else
            echo repo $REPO_URL problem - both public keys are not the same. Skipping
          fi
        fi
      fi
      LINE_NUM=$LINE_NUM+1
    else
      REPO_DIR=${REPO_URL//[*]/}
      if [ ! -d "$REPO_DIR" ]; then
        echo Repo directory $REPO_DIR not found. Skipping
      elif [ ! -f "${REPO_URL/[*]/app.repo.updates}" ]; then
        echo "Repo directory $REPO_URL without app.repo.updates file. Skipping"
      else
        if cmp -s $REPO_FIRST_PUBLIC_KEY $REPO_SECOND_PUBLIC_KEY; then
          while read -r line; do
            REPO_UPDATES="$REPO_UPDATES$line $(pwd)/$REPO_URL $(pwd)/$REPO_FIRST_PUBLIC_KEY
"
          done < "${REPO_URL/[*]/app.repo.updates}"
        else
          echo Repo $REPO_URL problem - both public keys are not the same. Skipping
        fi
      fi
    fi
  done < "${DIR}etc/app.repos"
#  echo "$REPO_UPDATES"
}

install_system_apps() {
  abc=$( echo dialog --stdout --backtitle \"PLLinux\\apps\\install from repo\" --cancel-label "Back" \
         --visit-items --item-help   \
         --buildlist \"Marking apps for deleting - installed on left, marked for delete on right\" 0 0 10 $(all_system_apps))
  cmd=$(eval $abc)

  if [ $? = 0 ]; then
    list=""
    listnr=1
  fi
}

install_from_file() {
    cmd=$(dialog --stdout --backtitle "PLLinux\device manager" --cancel-label "Back" --title "Welcome to the device manager" --fselect / 100 100)
}

set_system_apps() {
  while true; do
    cmd=$(dialog --stdout --backtitle "PLLinux\apps" --cancel-label "Back" --menu "Manage apps in the /app" 0 0 8 \
       1 "Install from repo" 2 "Install from file"  3 Delete )
    if [ $? = 0 ]; then
      case $cmd in
      1) install_system_apps ;;
      2) install_from_file ;;
      3) delete_system_apps ;;
      esac
    else
      break;
    fi
  done
}

swap_file() {
    cmd=$(dialog --stdout --backtitle "PLLinux\\swap file" --cancel-label "Back" \
      --form "Pls provide swap params" 0 0 8 \
      "Size in MB (0 disables it)" 1 1 "0" 1 50 10 0 \
      "How aggressive is moving to swap (0-100)" 2 1 "10" 2 50 10 0 \
      "Using zswap (compress RAM before saving to swap)" 3 1 "1" 3 50 10 0 )
    if [ $? == 0 ]; then
        linenr=1
        while read -r line; do
          case $linenr in
          1) if [ "$line" = "0" ]; then
               swapoff /swapfile
               rm /swapfile
             else
               swapoff /swapfile || true
               rm /swapfile || true
               fallocate -l ${line}M /swapfile
               chmod 600 /swapfile
               mkswap /swapfile
               swapon /swapfile
             fi ;;
          2) sysctl vm.swappiness=$line ;;
          esac
          linenr=$(($linenr+1))
        done <<< "$cmd"
    fi
}

network() {
    cmd=$(dialog --stdout --backtitle "PLLinux\\network" --cancel-label "Back" \
      --form "Pls provide params" 0 0 8 \
      "IP4 address for eth0 (empty = DHCP)" 1 1 "" 1 50 20 0 \
      "Enabling eth0 in system startup (0 or 1)" 2 1 "0" 2 50 20 0 )
    if [ $? == 0 ]; then
        linenr=1
#        while read -r line; do
#          case $linenr in
#          1) if [ "$line" = "0" ]; then
#               swapoff /swapfile
#               rm /swapfile
#             else
#               swapoff /swapfile || true
#               rm /swapfile || true
#               fallocate -l ${line}M /swapfile
#               chmod 600 /swapfile
#               mkswap /swapfile
#               swapon /swapfile
#             fi ;;
#          2) sysctl vm.swappiness=$line ;;
#          esac
#          linenr=$(($linenr+1))
#        done <<< "$cmd"
    fi
}

CFGFILE="etc/pllinux.conf"
if [ "$1" = "BOOT" ]; then
  set_general_config 1
  exit
else
  set_general_config 0
  if [ "$1" = "LANG" ]; then
    echo $LANG
    exit
  elif [ "$1" = "KEYB" ]; then
    echo $KEYB
    exit
  elif [ "$1" = "FONT" ]; then
    echo $FONT
    exit
  fi
fi

while true; do
  cmd=$(dialog --stdout --backtitle "PLLinux" --cancel-label "Quit" --menu "Welcome to the PLLinux configuration" 0 0 20 \
       1 "Apps" \
       2 "Background scheduled tasks for system and all users" \
       3 "Background services (dinit)" \
       4 "Device manager" \
       5 "Network firewall" \
       6 "Time" \
       7 "Kernel modules (modprobe)" \
       8 "Kernel params (sysctl)" \
       9 "Kernel logs (dmesg, press q to return)" \
       10 "System logs saved in files (syslogd)" \
       11 "Users" \
       12 "Network             - manual, IP4 DHCP" \
       14 "Swap file           - off" \
       15 "App language (todo) - $LANG" \
       16 "Keyboard and font   - $KEYB, $FONT" \
       17 "Timezone            - $TIMEZONE" \
       18 "Partition encryption password (todo)" \
       19 "Install or clone PLLinux to other partition" \
       20 "Setup UEFI boot menu (todo)" \
       21 "Setup UEFI fat32 boot partition (todo)" )
  if [ $? == 0 ]; then
    case $cmd in
    1) set_system_apps ;;
    2) tasks "crontab" ;;
    3) services ;;
    4) devices ;;
    8) sysctl_kernel_params ;;
    9) dmesg | less # it seems, that msgbox and other dialog elements have size limit
       ;;
    10) logs ;;
    11) set_users ;;
    12) network ;;
    14) swap_file ;;
    16) NEW_KEYB="$KEYB"
        NEW_FONT="$FONT"
        set_keyboard_font_general_or_user "" ;;
    17) set_time_zone ;;
    19) install_to 1 ;;
    20) dialog --backtitle "PLLinux\setup UEFI boot menu" --msgbox "$(efibootmgr)" 100 90 ;;
    esac
  else
    break
  fi
done

clear
set_general_config 0
