# Created by script pllinux version from 2 Aug 2026
KEYB=qwerty/pl4.map.gz
FONT=LatGrkCyr-12x22.psfu.gz
TIMEZONE=Europe/Warsaw
LANG=en_US.utf8
user2_APPS=mc current:util-linux current:busybox current:openssl current:groff current
user_FEATURES= proc processesall mnt network reset
user_APPS=bash current:busybox current:gcc current:git current:glib current:glibc current:groff current:kbd current:less current:mc current:ncurses current:nftables current:openssl 260725_3.6.3:openssl 260725_4.0.1:openssl current:util-linux current:zlib current:zstd current
