#!/app/busybox/current/bin/sh
DIR=$(/app/busybox/current/bin/dirname $0)
/app/ldso/current/ld.so --library-path /app/libtinfo/current:/app/libc/current:$DIR/lib:$DIR/lib/x86_64-linux-gnu $DIR/sbin/nft $@
